### ISSUE TITLE
Python 3.6 format string

### ISSUE THREAD

**Issue by wizardforcel** [mattharrison/Tiny-Python-3.6-Notebook#17]
```py
>>> name = 'Wizard'
>>> f'Hello, {name}!'
'Hello, Wizard!'
```
I found it's missed.

**Comment by mattharrison** [comment]
Not sure what this bug is. There is an example of f-strings in the String Formatting sectoin

**Comment by wizardforcel** [comment]
Sorry. I didn't notice it's in that section.
