### ISSUE TITLE
Context Managers example will not return expected text

### ISSUE THREAD

**Issue by FHeilmann** [mattharrison/Tiny-Python-3.6-Notebook#2]
>>> def start(env):
    ...     return '\begin{}'.format(env)

will cause `start('center')` to return `egincenter`. You need to escape the backslash and the curly braces like so:

    >>> def start(env):
    ...     return '\\begin{{{}}}'.format(env)

same for `end(env)`:

    >>> def end(env):
    ...      return '\\end{{{}}}'.format(env)

edit:

the same applies for Function Based Context Managers and Class Based Context Managers

**Comment by mattharrison** [comment]
Fixed by your PR. THanks
