### ISSUE TITLE
Ask permission to translate it to Chinese

### ISSUE THREAD

**Issue by veelion** [mattharrison/Tiny-Python-3.6-Notebook#8]
It is a awesome notebook. Can I translate it to Chinese？

**Comment by mattharrison** [comment]
@veelion There are one or two other efforts at translation. Note the license. I would ask the translations be made in branches and not distributed or made available commercially.

**Comment by veelion** [comment]
@mattharrison That's great, I can help to check the translation when it is done. A good book always be liked by many many books!
